export { default as Navbar } from "./navbar/Navbar";
export { default as Banner } from "./banner/Banner";
export { default as Title } from "./title/Title";
export { default as Courses } from "./courses/Courses";
export { default as CourseCard } from "./courseCard/CourseCard";
export { default as Stars } from "./stars/Stars";
export { default as Instructor } from "./instructor/Instructor";
export { default as Footer } from "./footer/Footer";
// export { default as Breadcrumb } from "./breadcrumb/Breadcrumb";
export { default as Pagination } from "./pagination/Pagination";
// export { default as DetailAside } from "./detailAside/DetailAside";
export { default as DetailHeader } from "./detailHeader/DetailHeader";
export { default as DetailTabs } from "./detailTabs/DetailTabs";
export { default as DetailCurriculum } from "./detailCurriculum/DetailCurriculum";
export { default as DetailDescription } from "./detailDescription/DetailDescription";
export { default as DetailInstructor } from "./detailInstructor/DetailInstructor";
export { default as DetailReviews } from "./detailReviews/DetailReviews";
// export { default as StyleSwitcher } from "./styleSwitcher/StyleSwitcher";
export { default as ScrollToTop } from "./scrollToTop/ScrollToTop";
